# deploy.yml
name: deploy django uwsgi nginx

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ubuntu
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/hanwooplz
            . hanwooplz_env/bin/activate
            git switch main
            git pull
            pip3 install -r requirements.txt
            sudo systemctl restart uwsgi nginx